### ISSUE TITLE
Vårdgivardashboard

### ISSUE THREAD

**Issue by Exsempelll** [DanyD4/Healthcare-server-B#23]
- [ ] För att möjliggöra effektiv hantering för vårdgivare behövs en dashboard där de kan se och uppdatera sitt schema och möten.
- [ ] Frontend: Design och funktionalitet för schema och tillgänglighet.
- [ ] Backend: API för schemauppdateringar och databasstruktur för lagring av schemainformation
